---
output: html_document
title: >
  STA 032 - Gateway to Data Science: Spring 2023
author: "STA 032"

---

**Instructor**: Jingwei Xiong: jwxxiong@ucdavis.edu

**TA**: Xiawei Wang: xxwwang@ucdavis.edu

**Class time**:   
Lectures are Mondays, Wednesdays and Fridays, 9-9:50 AM at Wellman 6  
Discussions (labs) are run by TA on Thursdays 10:00 - 10:50 AM (Section A01), 11:00 - 11:50 AM (Section A02) at TLC 2212.

**Office hours**:  
: TBD
Jingwei Xiong: TBD

**Canvas**: [here](https://canvas.ucdavis.edu/courses/784688).

**Syllabus**: [here](https://xjw1001001.github.io/syllabus/syllabus.html).

**Piazza**: [here](https://canvas.ucdavis.edu/courses/784688/external_tools/12776).

**Gradescope**: [here](https://www.gradescope.com/courses/524102).

<!-- your comment 
**Textbooks**:
There are three optional textbooks. They are all available online and are free. 

1. R for Data Science by Hadley Wickham and Garrett Grolemund. 1st Edition, 2017. Available [here](https://r4ds.had.co.nz/index.html).
2. Statistics for Engineers and Scientists, Fifth Edition}, William Navidi.  Older versions will be fine.)
3. OpenIntro Statistics by David Diez, Mine Cetinkaya-Rundel and Christopher Barr. 4th Edition, 2019. Available [here](https://www.openintro.org/book/os/).

-->

## Class Schedule

### Week 1: Introduction, R programming basics
- **Homework 0**: [Check in](https://canvas.ucdavis.edu/courses/784688/assignments/1035051)

- Mon April 3: Introduction, R, Rstudio
  - Notes: [Lecture 1](https://xjw1001001.github.io/lecture/Lecture 1/lecture1.html)
  - Reading: 
    - [Getting started with R and RStudio](http://rafalab.dfci.harvard.edu/dsbook/getting-started.html)
    - [R markdown](http://rafalab.dfci.harvard.edu/dsbook/reproducible-projects-with-rstudio-and-r-markdown.html#r-markdown)
    - [R markdown tutorial](https://rmarkdown.rstudio.com/lesson-1.html)
    - R for Data Science Chapters 1, 2, 27


- Wed April 5: Overview of data types and data structures, vectors
  - Notes: [Lecture 2](https://xjw1001001.github.io/lecture/Lecture 2/lecture2.html)
  - Reading: 
    - R for Data Science Chapter 4, 20
    - Additional reading: Matloff Chapter 2
    - [Chapter 2:R basics](http://rafalab.dfci.harvard.edu/dsbook/r-basics.html)

- Fri April 7: More on Vectors, R markdown Homework example
  - Notes: [Lecture 3](https://xjw1001001.github.io/lecture/Lecture 3/lecture3.html)
  - Reading: 
    - R for Data Science Chapter 20, 27
    - Additional reading: Matloff Chapter 2
    - [Chapter 2:R basics](http://rafalab.dfci.harvard.edu/dsbook/r-basics.html)
    - [R markdown tutorial](https://rmarkdown.rstudio.com/lesson-1.html)
  - **Homework 1**: (Due April 17 midnight, cover lecture 1-4) [Html](https://xjw1001001.github.io/homework/homework1/HW1.html) [Rmd](https://xjw1001001.github.io/homework/homework1/HW1.Rmd)
    
### Week 2: Introduction to data manipulation

- Mon April 10: List and data frame
  - Notes: [Lecture 4](https://xjw1001001.github.io/lecture/Lecture 4/lecture4.html)
  - Reading: 
    - R for Data Science Chapter 4, 20
    - [Chapter 2:R basics](http://rafalab.dfci.harvard.edu/dsbook/r-basics.html)
    - [Chapter 3](http://rafalab.dfci.harvard.edu/dsbook/programming-basics.html)
    

- Wed April 12: Data Manipulation 1
  - Notes: [Lecture 5](https://xjw1001001.github.io/lecture/Lecture 5/lecture5.html)
  - Reading: 
    - [Chapter 4:The tidyverse](http://rafalab.dfci.harvard.edu/dsbook/tidyverse.html)
    - R for Data Science Chapter 5

- Fri April 14: Data Manipulation 2, intro to data visualization
  - Notes: [Lecture 6](https://xjw1001001.github.io/lecture/Lecture 6/lecture6.html)
  - Reading: 
    - [Chapter 4:The tidyverse](http://rafalab.dfci.harvard.edu/dsbook/tidyverse.html)
    - [Data Wrangling with Tidyverse](https://hbctraining.github.io/Intro-to-R/lessons/tidyverse_data_wrangling.html)
    - [Chapter 7:Introduction to data visualization](http://rafalab.dfci.harvard.edu/dsbook/introduction-to-data-visualization.html)

  - **Homework 2**: (Due April 26 midnight, cover lecture 5-8) [Html](https://xjw1001001.github.io/homework/homework2/HW2.html) [Rmd](https://xjw1001001.github.io/homework/homework2/HW2.Rmd)
  
### Week 3: Introduction to data visualization, descriptive statistics
- **Homework 1: (Due April 17 midnight)**

- Mon April 17: Data visualization 1
  - Notes: [Lecture 7](https://xjw1001001.github.io/lecture/Lecture 7/lecture7.html)
  - Reading: 
    - [Chapter 7:Introduction to data visualization](http://rafalab.dfci.harvard.edu/dsbook/introduction-to-data-visualization.html)
    - [Chapter 8:ggplot2](http://rafalab.dfci.harvard.edu/dsbook/ggplot2.html)

    
- Wed April 19: Data visualization 2, descriptive statistics
  - Notes: [Lecture 8](https://xjw1001001.github.io/lecture/Lecture 8/lecture8.html)
  - Reading: 
    - [Chapter 10:Data visualization in practice](http://rafalab.dfci.harvard.edu/dsbook/gapminder.html)
    - [Open Intro Statistics Chapter 1](https://www.webpages.uidaho.edu/~stevel/251/slides/os2_slides_01.pdf)

- Fri April 21: Describing numerical distributions
  - Notes: [Lecture 9](https://xjw1001001.github.io/lecture/Lecture 9/lecture9.html)
  - Reading:
    - [Open Intro Statistics Chapter 1](https://www.webpages.uidaho.edu/~stevel/251/slides/os2_slides_01.pdf)
  - **Homework 3**: (Due May 3 midnight, cover lecture 9-11) [Html](https://xjw1001001.github.io/homework/homework3/HW3.html) [Rmd](https://xjw1001001.github.io/homework/homework3/HW3.Rmd)

### Week 4: Descriptive Statistics: Numerical and Categorical Data

- Mon April 24: Describing Numerical and Categorical Data
  - Notes: [Lecture 10](https://xjw1001001.github.io/lecture/Lecture 10/lecture10.html)
  - Reading: 
    - R for Data Science Chapter 7
    - [Chapter 9 Visualizing data distributions](http://rafalab.dfci.harvard.edu/dsbook/dataviz-distributions.html)
    
- Wed April 26: Describing Numerical and Categorical Data, customizing plots
  - Notes: [Lecture 11](https://xjw1001001.github.io/lecture/Lecture 11/lecture11.html)
  - Reading: 
    - [Chapter 10 Data visualization in practice](http://rafalab.dfci.harvard.edu/dsbook/gapminder.html)
    - [Chapter 11 Data visualization principles](http://rafalab.dfci.harvard.edu/dsbook/data-visualization-principles.html)
  - **Homework 2: (Due April 26 midnight)**

- Fri April 28: Introduction to Probability
  - Notes: [Lecture 12](https://xjw1001001.github.io/lecture/Lecture 12/lecture12.html)

#### **Midterm 1: (Due April 29 midnight, cover lecture 1-12)**
  - Open book take home exam
  - It's **highly recommended** to finish the homework 1,2,3 before midterm 1.
  
### Week 5: Probability and distributions
- Mon May 1: Introduction to Probability
  - Notes: [Lecture 13](https://xjw1001001.github.io/lecture/Lecture 13/lecture13.html)
  - **Homework 4**: (Due May 12 midnight, cover lecture 12-15) [Html](https://xjw1001001.github.io/homework/homework4/HW4.html) [Rmd](https://xjw1001001.github.io/homework/homework4/HW4.Rmd)
  
- Wed May 3: Random Variables and Distributions
  - Notes: [Lecture 14](https://xjw1001001.github.io/lecture/Lecture 14/lecture14.html)
  - **Homework 3: (Due May 3 midnight)**
  
- Fri May 5: Binomial distribution, simulation, R function
  - Notes: [Lecture 15](https://xjw1001001.github.io/lecture/Lecture 15/lecture15.html)

### Week 6: More on distributions
- Mon May 8: Poisson and Normal (Gaussian) Distribution
  - Notes: [Lecture 16](https://xjw1001001.github.io/lecture/Lecture 16/lecture16.html)
  - **Homework 5**: (Due May 21 midnight, cover lecture 16-19) [Html](https://xjw1001001.github.io/homework/homework5/HW5.html) [Rmd](https://xjw1001001.github.io/homework/homework5/HW5.Rmd)

- Wed May 10: 
  - Notes: [Lecture 17](https://xjw1001001.github.io/lecture/Lecture 17/lecture17.html)

- Fri May 12: 
  - Notes: [Lecture 18](https://xjw1001001.github.io/lecture/Lecture 18/lecture18.html)
  - **Homework 4: (Due May 12 midnight)**
  
### Week 7: 
- Mon May 15: 
  - Notes: [Lecture 19](https://xjw1001001.github.io/lecture/Lecture 19/lecture19.html)
 
- Wed May 17: 
  - Notes: [Lecture 20](https://xjw1001001.github.io/lecture/Lecture 20/lecture20.html)
  - **Homework 6**: (Due May 28 midnight, cover lecture 20-23) [Html](https://xjw1001001.github.io/homework/homework5/HW5.html) [Rmd](https://xjw1001001.github.io/homework/homework5/HW5.Rmd)


- Fri May 19: 
  - Notes: [Lecture 21](https://xjw1001001.github.io/lecture/Lecture 21/lecture21.html)
  
### Week 8: 
- Mon May 22: 
  - Notes: [Lecture 22](https://xjw1001001.github.io/lecture/Lecture 22/lecture22.html)
    
- Wed May 24: 
  - Notes: [Lecture 23](https://xjw1001001.github.io/lecture/Lecture 23/lecture23.html)

- Fri May 26: Midterm 2 (In person)
  
### Week 9: 
- Mon May 29: Memorial Day, no class
    
- Wed May 31: 
  - Notes: [Lecture 24](https://xjw1001001.github.io/lecture/Lecture 24/lecture24.html)

- Fri Jun 2: 
  - Notes: [Lecture 25](https://xjw1001001.github.io/lecture/Lecture 25/lecture25.html)

### Week 10: 
- Mon Jun 5: 
  - Notes: [Lecture 26](https://xjw1001001.github.io/lecture/Lecture 26/lecture26.html)  
  
- Wed Jun 7: 
  - Notes: 

  
<!-- your comment 


- Wed April 5: Overview of data types and data structures, vectors
  - Notes: [Lecture 2](https://xhtai.github.io/statdatasci/lectures/lecture2/lecture2.html)
  - Reading: 
    - R for Data Science Chapter 4, 20
    - Additional reading: Matloff Chapter 2

- Fri April 7: Overview of data types and data structures, vectors
  - Notes: [Lecture 3](https://xhtai.github.io/statdatasci/lectures/lecture2/lecture2.html)
  - Reading: 
    - R for Data Science Chapter 4, 20
    - Additional reading: Matloff Chapter 2

### Week 3: Introduction to data visualization
- Mon April 3: Introduction and R Basics
  - Notes: [Lecture 1](https://xhtai.github.io/statdatasci/lectures/lecture1/lecture1.html)
  - Reading: 
    - R for Data Science Chapters 1, 2, 27

- Wed April 5: Overview of data types and data structures, vectors
  - Notes: [Lecture 2](https://xhtai.github.io/statdatasci/lectures/lecture2/lecture2.html)
  - Reading: 
    - R for Data Science Chapter 4, 20
    - Additional reading: Matloff Chapter 2

- Fri April 7: Overview of data types and data structures, vectors
  - Notes: [Lecture 3](https://xhtai.github.io/statdatasci/lectures/lecture2/lecture2.html)
  - Reading: 
    - R for Data Science Chapter 4, 20
    - Additional reading: Matloff Chapter 2

### Week 4: Data visualization tools, Descriptive statistics


### Week 5: Data visualization tools, Descriptive statistics



### Week 2: Overview of data types
- Mon Sept 26: More on vectors, arrays
  - Notes: [Lecture 3](https://xhtai.github.io/statdatasci/lectures/lecture3/lecture3.html)
  - Reading: 
    - R for Data Science Chapter 20
    - Additional reading: Matloff Chapter 3
  
- Wed Sept 28: Arrays, matrices, lists
  - Notes: [Lecture 4](https://xhtai.github.io/statdatasci/lectures/lecture4/lecture4.html)
  - Reading: 
    - R for Data Science Chapter 20 
    - Additional reading: Matloff Chapters 3, 4 

- Fri Sept 30: Lists, data frames, exploratory data analysis
  - Notes: [Lecture 5](https://xhtai.github.io/statdatasci/lectures/lecture5/lecture5.html)
  - Reading: 
    - Additional reading: Matloff Chapter 5
  - Homework 1: [Html](https://xhtai.github.io/statdatasci/homework/homework1/HW1.html) [Rmd](https://xhtai.github.io/statdatasci/homework/homework1/HW1.Rmd)
  
  
  
### Week 3: Data manipulation and data visualization tools
- Mon Oct 3: Exploratory data analysis, data manipulation tools 
  - Notes: [Lecture 6](https://xhtai.github.io/statdatasci/lectures/lecture6/lecture6.html)
  - Reading: 
    - R for Data Science Chapter 5

- Wed Oct 5: Data manipulation and visualization tools 
  - Notes: [Lecture 7](https://xhtai.github.io/statdatasci/lectures/lecture7/lecture7.html)
  - Reading: 
    - R for Data Science Chapter 3 

- Fri Oct 7: Data visualization tools 
  - Notes: [Lecture 8](https://xhtai.github.io/statdatasci/lectures/lecture8/lecture8.html)
  - Reading: 
    - R for Data Science Chapter 3 
  - Homework 2: [Html](https://xhtai.github.io/statdatasci/homework/homework2/HW2.html) [Rmd](https://xhtai.github.io/statdatasci/homework/homework2/HW2.Rmd)
  

### Week 4: Data visualization tools, Descriptive statistics
- Mon Oct 10: Data visualization tools, descriptive statistics 
  - Notes: [Lecture 9](https://xhtai.github.io/statdatasci/lectures/lecture9/lecture9.html)
  - Reading: 
    - Open Intro Statistics Chapter 1

- Wed Oct 12: Describing numerical distributions
  - Notes: [Lecture 10](https://xhtai.github.io/statdatasci/lectures/lecture10/lecture10.html)
  - Reading: 
    - Open Intro Statistics Chapter 2 

- Fri Oct 14: Numerical and categorical data 
  - Notes: [Lecture 11](https://xhtai.github.io/statdatasci/lectures/lecture11/lecture11.html)
  - Reading: 
    - R for Data Science Chapter 7
  - Homework 3: [Html](https://xhtai.github.io/statdatasci/homework/homework3/HW3.html) [Rmd](https://xhtai.github.io/statdatasci/homework/homework3/HW3.Rmd)
  

### Week 5: Descriptive statistics
- Mon Oct 17: Numerical and categorical data
  - Notes: [Lecture 12](https://xhtai.github.io/statdatasci/lectures/lecture12/lecture12.html)
  
- Wed Oct 19: Review

- Fri Oct 21: Midterm 1

### Week 6: Introduction to probability
- Mon Oct 24: Introduction to probability 
  - Notes: [Lecture 13](https://xhtai.github.io/statdatasci/lectures/lecture13/lecture13.html)
  - Reading: 
    - Open Intro Statistics Chapter 3.1
  
- Wed Oct 26: Conditional, marginal and joint probability; Bayes' Theorem
  - Notes: [Lecture 14](https://xhtai.github.io/statdatasci/lectures/lecture14/lecture14.html)
  - Reading: 
    - Open Intro Statistics Chapter 3.2

- Fri Oct 28: Random variables and common distributions
  - Notes: [Lecture 15](https://xhtai.github.io/statdatasci/lectures/lecture15/lecture15.html)
  - Reading: 
    - Open Intro Statistics Chapter 3.4, 3.5
  - Homework 4: [Html](https://xhtai.github.io/statdatasci/homework/homework4/HW4.html) [Pdf](https://xhtai.github.io/statdatasci/homework/homework4/HW4.pdf)
  
### Week 7: Common distributions
- Mon Oct 31: Bernoulli and binomial distribution
  - Notes: [Lecture 16](https://xhtai.github.io/statdatasci/lectures/lecture16/lecture16.html)
  - Reading: 
    - Open Intro Statistics Chapter 4.3
  
- Wed Nov 2: Binomial and Poisson distribution
  - Notes: [Lecture 17](https://xhtai.github.io/statdatasci/lectures/lecture17/lecture17.html)
  - Reading:
    - Open Intro Statistics Chapter 4.5

- Fri Nov 4: Poisson and Normal distribution
  - Notes: [Lecture 18](https://xhtai.github.io/statdatasci/lectures/lecture18/lecture18.html)
  - Reading: 
    - Open Intro Statistics Chapter 4.1
  - Homework 5: [Html](https://xhtai.github.io/statdatasci/homework/homework5/HW5.html) [Pdf](https://xhtai.github.io/statdatasci/homework/homework5/HW5.pdf) [Rmd](https://xhtai.github.io/statdatasci/homework/homework5/HW5.Rmd)

### Week 8: Normal distribution, sampling distributions 
- Mon Nov 7: Normal distribution, sampling distributions
  - Notes: [Lecture 19](https://xhtai.github.io/statdatasci/lectures/lecture19/lecture19.html)
  - Reading: 
    - Open Intro Statistics Chapter 5.1 
  
- Wed Nov 9: Sampling distribution of sample mean and proportion
  - Notes: [Lecture 20](https://xhtai.github.io/statdatasci/lectures/lecture20/lecture20.html)

- Fri Nov 11: Veterans Day

### Week 9: Confidence intervals 
- Mon Nov 14: Introduction to confidence intervals 
  - Notes: [Lecture 21](https://xhtai.github.io/statdatasci/lectures/lecture21/lecture21.html)
  - Reading:
    - Open Intro Statistics Chapter 5.2 
  - Homework 6: [Html](https://xhtai.github.io/statdatasci/homework/homework6/HW6.html) [Pdf](https://xhtai.github.io/statdatasci/homework/homework6/HW6.pdf) [Rmd](https://xhtai.github.io/statdatasci/homework/homework6/HW6.Rmd)
- Wed Nov 16: Review
- Fri Nov 18: Midterm 2

### Week 10: Confidence intervals 
- Mon Nov 21: Confidence intervals for population mean and proportion 
  - Notes: [Lecture 22](https://xhtai.github.io/statdatasci/lectures/lecture22/lecture22.html)
  - Reading:
    - Open Intro Statistics Chapter 7.1.1-7.1.4
- Wed Nov 23, Fri Nov 25: Thanksgiving 

### Week 11: Hypothesis testing 
- Mon Nov 28: Hypothesis testing framework and errors 
  - Notes: [Lecture 23](https://xhtai.github.io/statdatasci/lectures/lecture23/lecture23.html)
  - Reading:
    - Open Intro Statistics Chapter 5.3
  - Homework 7: [Html](https://xhtai.github.io/statdatasci/homework/homework7/HW7.html) [Pdf](https://xhtai.github.io/statdatasci/homework/homework7/HW7.pdf) [Rmd](https://xhtai.github.io/statdatasci/homework/homework7/HW7.Rmd)
- Wed Nov 30: Hypothesis testing for population mean and proportion 
  - Notes: [Lecture 24](https://xhtai.github.io/statdatasci/lectures/lecture24/lecture24.html)
  - Reading:
    - Open Intro Statistics Chapter 6.1
- Fri Dec 2: Confidence intervals and one-sided tests 
  - Notes: [Lecture 25](https://xhtai.github.io/statdatasci/lectures/lecture25/lecture25.html)

-->



