---
title: "Introduction to data science 1"
subtitle: "<br><br> STA 032: Gateway to data science Lecture 5"
author: "Jingwei Xiong"
date: April 10, 2023
output:
  xaringan::moon_reader:
    # css: [default, metropolis, metropolis-fonts]
    # css: ["default", "extra.css"]
    # css: ["../xaringan-themer.css", "../slides.css"]
    # lib_dir: libs
    nature:
      # ratio: "16:9"
      # highlightLines: true
      # highlightStyle: solarized-light
      countIncrementalSlides: false
---

```{r, echo = FALSE}
#library(renderthis)
#to_pdf(from = "lecture1.Rmd",complex_slides = TRUE)
```


```{r xaringanExtra, echo=FALSE}
xaringanExtra::use_xaringan_extra(c("tile_view", "animate_css", "tachyons"))
xaringanExtra::use_panelset()
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "",eval = TRUE,fig.retina = 2, message=F, warning = F
)
```

```{r packages, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(unvotes)
```


```{css, echo = FALSE}
.tiny .remark-code { font-size: 60%; }
.small .remark-code { font-size: 80%; }
```

---

## Today

- Introduction to lists

- Data frames, or more generally "data sets"

- Auto complete and How to use help in R

???

Today's topics are lists and data frames, which are both important data structures in R.

---

---


# Readings
